export const projects = [
  {
    title: 'Enjoy places',
    description: "It's a website that provides detailed information about places before visiting them and check if they are suitable to serve people in general and people who are using wheelchair in particular.",
      image: '/images/enjoyPlace.png',
      tags: ['Node.js', 'React.js', 'Postgres'],
    source: 'https://google.com',
    visit: 'https://github.com/MocaSrour/EnjoyPlace',
    id: 0,
  },
  {
    title: "Moca's Movies",
    description:'A website that helps the client to rate, give reviews and watch movies and animes and adding them to favorite list.',
    image: '/images/11.png',
    tags: ['Asp.net', 'C#'],
    source: 'https://google.com',
    visit: 'https://github.com/MocaSrour/Projects-MocaMovies',
    id: 1,
  },
  {
    title: 'Beyond Consulting Ltd.',
    description: "Developing a customized Dashboard, Monitoring and Evaluation System that covers HCAC's new Strategic and Action plans and serves as HCAC's main system for measuring progress levels.",
      image: '/images/beyond.png',
      tags: ['Asp.net', 'C#', 'MySQL'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Magento',
    description: "Website to shop the latest fashion trends and elevate your wardrobe with stylish clothing for every occasion.",
      image: '/images/magento.png',
      tags: ['Maven', 'TestNG', 'Cucumber'],
    source: 'https://magento.softwaretestingboard.com/',
    visit: 'https://github.com/MocaSrour/magento',
    id: 3,
  },
  {
    title: "Automation Test Store",
    description:'This store has been created to enable students to practice their automation testing skills. This is not a real store, no orders are actually placed or payments taken. This store is to be used for educational purposes only.',
      image: '/images/automationteststore.png',
      tags: ['Maven', 'TestNG', 'Cucumber'],
    source: 'https://automationteststore.com/',
    visit: 'https://github.com/MocaSrour/automationTestStore',
    id: 4,
  },
  {
    title: 'Almosafer',
    description: "Website offering consumers seamless user experiences for domestic and international travel bookings.",
      image: '/images/almosafer.png',
      tags: ['Maven', 'TestNG', 'Cucumber'],
    source: 'https://global.almosafer.com/en',
    visit: 'https://github.com/MocaSrour/Almosafer',
    id: 5,
  },
  {
    title: 'Jupiter Toys',
    description: "Engaging e-commerce platform designed for selling high-quality stuffed animal toys.",
      image: '/images/Jupiter.png',
      tags: ['Maven', 'TestNG', 'Cucumber'],
    source: 'https://jupiter.cloud.planittesting.com/#',
    visit: 'https://github.com/MocaSrour/JupiterToys',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];
